allowBuilds:
  "@sentry/cli": true
  core-js: false
  core-js-pure: false
  es5-ext: false
  esbuild: true
  gatsby: true
  gatsby-cli: false
  lmdb: true
  msgpackr-extract: true
  msw: true
  sharp: true
  workerd: true
minimumReleaseAge: 3
shamefullyHoist: true
strictDepBuilds: false
minimumReleaseAgeExclude:
  # Renovate security update: dompurify@3.4.9
  - dompurify@3.4.9
