name: lint content

on:
  push:
    paths:
      - 'content/blog/**/*.md'

jobs:
  textlint:
    runs-on: ubuntu-latest
    name: run textlint
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: lint check markdown
        run: |
          pnpm install
          pnpm lint:md
