name: slack notification

on:
  workflow_run:
    workflows:
      - ci
      - lint content
      - Playwright Tests
    types:
      - completed
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@2e709ce51fd47f02b7221db8547e6e6f49f81f1d # v2.0.0
        with:
          workflow_run: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: swfz/failed-log-to-slack-action@5e26213c694dbc972a06e6cfab2e31db7453f164 # v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

