name: slack notification

on:
  workflow_run:
    workflows:
      - ci
      - lint content
      - Playwright Tests
    types:
      - completed
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: swfz/slack-workflow-status@feature/follow-workflow-run-trigger
        with:
          workflow_run: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: swfz/failed-log-to-slack-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

